return {
    toolshed_plugin_name = 'vrighter/toolshed.nvim',
    cache_plugin_name = 'lewis6991/impatient.nvim',
    mapx = 'b0o/mapx.nvim',
    type = {
        cache = 0,
        global = 1,
        theme = 2,
        sys_override = 3,
        plugtool = 4,
        update = 5,
        generic_plugin = 6,
        util = 7,
        lsp = 8,
        dap = 9,
        dev = 10,
        plugin = 11,
        gui = 12,
    },
}
